name: Build Release APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup secrets
      run: |
        base64 -d {{ secrets.RELEASE_KEYSTORE }} > app/release.keystore
        base64 -d {{ secrets.RELEASE_KEYSTORE_PASSWORD }} > app/passwords.properties
    - uses: actions/setup-java@v3
      with:
        java-version: 17
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: client
        path: app/build/outputs/apk/debug/app-release.apk